version: "3.8"

services:
  pg:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_project_dev

volumes:
  pgdata:
